version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
    expose:
      - "8000"

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${PORT}:80

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    expose:
      - "27017"
